# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrObservr < Formula
  desc "herdr-observr — agent runtime health telemetry for herdr exported over OTLP."
  homepage "https://github.com/nabutabu/herdr-observr"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.11/herdr-observr_0.0.11_darwin_amd64.tar.gz"
      sha256 "716a819faac9dc7e622014e8909aaa8244f56e11ef628a50d6f6b94f78b72331"

      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.11/herdr-observr_0.0.11_darwin_arm64.tar.gz"
      sha256 "6cba5a9dc8033913e9153f1cb596a39751c4692c14771ba632d99b35dffaff86"

      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.11/herdr-observr_0.0.11_linux_amd64.tar.gz"
      sha256 "21480e7cb8dfb187ee7f5ba5fd41ff82ce72df8b04ef0369cb74ac11b5277b26"
      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.11/herdr-observr_0.0.11_linux_arm64.tar.gz"
      sha256 "029629f1ff352d1ee43567936893557fb8a8ea34251e357d4f56e7a4e268520e"
      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
  end

  test do
    assert_path_exists bin/"herdr-observr"
  end
end
