# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrObservr < Formula
  desc "herdr-observr — agent runtime health telemetry for herdr exported over OTLP."
  homepage "https://github.com/nabutabu/herdr-observr"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.5/herdr-observr_0.0.5_darwin_amd64.tar.gz"
      sha256 "e9f327c85ecc0b4ae152ea9d127f86c327211373998d08c840706fa4ea3736f9"

      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.5/herdr-observr_0.0.5_darwin_arm64.tar.gz"
      sha256 "9b3876042db9d7d4797f08ac534aca86a23c231fc9992785c319402ef27a56ce"

      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.5/herdr-observr_0.0.5_linux_amd64.tar.gz"
      sha256 "3d3e6b16bbe496dbeecdb88f12305158f09137443d14e501c047828b22b69cc3"
      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.5/herdr-observr_0.0.5_linux_arm64.tar.gz"
      sha256 "06c0a55902e38675a056fb64144450bac2c260d1915fb23ec68d4f0fa18ebff5"
      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
  end

  test do
    assert_path_exists bin/"herdr-observr"
  end
end
