# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrObservr < Formula
  desc "herdr-observr — agent runtime health telemetry for herdr exported over OTLP."
  homepage "https://github.com/nabutabu/herdr-observr"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.6/herdr-observr_0.0.6_darwin_amd64.tar.gz"
      sha256 "03f226a8a9a221f38030af3ebef3eef43197119a0d47cc9fc8f3c59ca2eaa9a4"

      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.6/herdr-observr_0.0.6_darwin_arm64.tar.gz"
      sha256 "a68c05b1e18139ad49e9ef0fe3cd23906e9b162ca7b00fbb5df878bae6d7269e"

      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.6/herdr-observr_0.0.6_linux_amd64.tar.gz"
      sha256 "160c2209c3a2a98de80417a17971a758f521f4022d40b545b83630a0334ad063"
      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nabutabu/herdr-observr/releases/download/v0.0.6/herdr-observr_0.0.6_linux_arm64.tar.gz"
      sha256 "de9c2b7cf9876c66557e87d3e35c72e7e7463a92278a294731191aa0e905973b"
      define_method(:install) do
        bin.install "herdr-observr"
      end
    end
  end

  test do
    assert_path_exists bin/"herdr-observr"
  end
end
